import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Manifest = {
  agent_name?: string;
  agent_description?: string;
  archetype?: string;
  persona_match?: string;
  core_capabilities?: string[];
  required_connectors?: string[];
  system_prompt_he?: string;
  first_tasks_he?: string[];
  guardrails_he?: string[];
};

/**
 * Public install endpoint — returns the agent definition as a markdown file
 * formatted for the target platform (Claude Code or Codex CLI).
 *
 * No auth required so `curl ... -o .claude/agents/<name>.md` works from any shell.
 * Templates are always public; user packages are public-by-id (the id is the auth).
 */
export async function GET(
  req: Request,
  ctx: { params: Promise<{ id: string }> }
) {
  const { id } = await ctx.params;
  const url = new URL(req.url);
  const platform = (url.searchParams.get("platform") ?? "claude-code") as
    | "claude-code"
    | "codex";

  const supabase = createServiceClient();

  type PkgRow = {
    id: string;
    name: string;
    description: string | null;
    archetype: string | null;
    manifest_json: Manifest | null;
    version: string;
  };

  // Try packages first
  const pkgRes = await supabase
    .from("packages")
    .select("id, name, description, archetype, manifest_json, version")
    .eq("id", id)
    .single();
  let pkg: PkgRow | null = (pkgRes.data as PkgRow | null) ?? null;

  // Fallback: treat id as consultation_id with completed analysis
  if (!pkg) {
    const { data: consultation } = await supabase
      .from("consultations")
      .select("id, analysis_json, status")
      .eq("id", id)
      .single();
    if (consultation && consultation.analysis_json) {
      const an = consultation.analysis_json as Manifest & { agent_name?: string };
      pkg = {
        id: consultation.id,
        name: an.agent_name ?? "GenerAgent agent",
        description: an.agent_description ?? null,
        archetype: an.archetype ?? null,
        manifest_json: an,
        version: "1.0.0",
      };
    }
  }

  if (!pkg) {
    return new NextResponse(`# Agent not found\n\nid: ${id}\n`, {
      status: 404,
      headers: { "content-type": "text/markdown; charset=utf-8" },
    });
  }

  const m: Manifest = pkg.manifest_json ?? {};
  const body = renderMarkdown({
    platform,
    name: pkg.name,
    description: pkg.description,
    archetype: pkg.archetype,
    version: pkg.version,
    manifest: m,
  });

  return new NextResponse(body, {
    status: 200,
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "cache-control": "public, max-age=300",
      "content-disposition": `inline; filename="generagent-${id.slice(0, 8)}.md"`,
    },
  });
}

function renderMarkdown(args: {
  platform: "claude-code" | "codex";
  name: string;
  description: string | null;
  archetype: string | null;
  version: string;
  manifest: Manifest;
}): string {
  const { platform, name, description, archetype, version, manifest } = args;
  const m = manifest;

  // Front-matter shape differs slightly between platforms.
  const frontmatter =
    platform === "claude-code"
      ? [
          "---",
          `name: ${slugify(name)}`,
          `description: ${escapeYaml(description ?? "")}`,
          ...(m.required_connectors && m.required_connectors.length > 0
            ? [`tools: ${m.required_connectors.join(", ")}`]
            : []),
          "---",
          "",
        ].join("\n")
      : [
          "---",
          `name: ${slugify(name)}`,
          `description: ${escapeYaml(description ?? "")}`,
          ...(archetype ? [`archetype: ${archetype}`] : []),
          "---",
          "",
        ].join("\n");

  const sections: string[] = [];
  sections.push(`# ${name}`);
  if (description) sections.push(description);
  sections.push(`\n_Generated by GenerAgent · v${version} · ${platform}_\n`);

  if (m.system_prompt_he) {
    sections.push("## System prompt\n");
    sections.push(m.system_prompt_he);
  }

  if (m.core_capabilities && m.core_capabilities.length > 0) {
    sections.push("## Core capabilities\n");
    sections.push(m.core_capabilities.map((c) => `- ${c}`).join("\n"));
  }

  if (m.required_connectors && m.required_connectors.length > 0) {
    sections.push("## Required tools / connectors\n");
    sections.push(m.required_connectors.map((c) => `- ${c}`).join("\n"));
  }

  if (m.first_tasks_he && m.first_tasks_he.length > 0) {
    sections.push("## First tasks to try\n");
    sections.push(m.first_tasks_he.map((t, i) => `${i + 1}. ${t}`).join("\n"));
  }

  if (m.guardrails_he && m.guardrails_he.length > 0) {
    sections.push("## Guardrails\n");
    sections.push(m.guardrails_he.map((g) => `- ${g}`).join("\n"));
  }

  return frontmatter + sections.join("\n\n") + "\n";
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9א-ת]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function escapeYaml(s: string): string {
  // Quote if contains special chars
  if (/[:#\n"]/.test(s)) return `"${s.replace(/"/g, '\\"').replace(/\n/g, " ")}"`;
  return s;
}
